default: &default
  #adapter: sqlite3
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  host: 
  adapter: postgresql
  encoding: unicode
  database: 
  port: 5432
  pool: 5
  username: 
  password: 

test:
  <<: *default
  database: db/test.sqlite3

production:
  host: 
  adapter: postgresql
  encoding: unicode
  database: 
  pool: 5
  username: 
  password: 
